#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="1.2.1"

SRC="/usr/local/src"
dl https://github.com/viewvc/viewvc/archive/${VERSION}.zip $SRC
mv $SRC/${VERSION}.zip $SRC/viewvc-${VERSION}.zip
