#!/bin/bash -ex

SRC=/usr/local/src

# configure apache
a2dissite 000-default
a2ensite revisioncontrol
a2enmod rewrite
a2enmod cgi
a2enmod cgid
a2enmod proxy
a2enmod proxy_http
a2disconf gitweb
a2enmod cgid

# configure viewvc
sed -i '
s|^#\(root_parents =\)[^=]*$|\1 /srv/repos/svn: svn|g;
s|^#\(root_as_url_component =\)[^=]*$|\1 1|g;
s|^#\(docroot =\)[^=]*$|\1 /docroot|g;
' /etc/viewvc/viewvc.conf

# configure integrated documentation
DOCS=/var/www/docs
tar -zxf $DOCS/svn.tar.gz -C $DOCS
rm $DOCS/*.tar.gz

ln -s /usr/share/doc/git-doc $DOCS/git

cat >> /etc/default/git-daemon << EOF

# fix Debian git-daemon silliness
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=740154

HOME=/nonexistent
EOF

# patch gitweb to force text/html (apache-credit)
OLD='my $content_type = get_content_type_html();'
NEW='my $content_type = "text/html";'
sed -i "s|$OLD|$NEW|" /usr/lib/cgi-bin/gitweb.cgi

# replace gitweb theme with a nicer one (github inspired)
GITWEB=/usr/share/gitweb
GITWEB_THEME=$SRC/gitweb-theme

[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY
git clone --depth=1 https://github.com/kogakure/gitweb-theme.git $GITWEB_THEME
unset HTTP_PROXY

$GITWEB_THEME/setup -v -t $GITWEB

useradd -d /srv/repos vcs
chown -R vcs:vcs /srv/repos

# configure tkl-webcp
sed -i "s|padding: 5pt 8px;|padding: 5pt 0px;|" /var/www/css/base.css

